// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: proto/dmgn/v1/dmgn.proto

package dmgnpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Memory is the core data structure (wire format for network transmission).
type Memory struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp        int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type             string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Embedding        []float32              `protobuf:"fixed32,4,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	EncryptedPayload []byte                 `protobuf:"bytes,5,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	Links            []string               `protobuf:"bytes,6,rep,name=links,proto3" json:"links,omitempty"`
	MerkleProof      string                 `protobuf:"bytes,7,opt,name=merkle_proof,json=merkleProof,proto3" json:"merkle_proof,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Memory) Reset() {
	*x = Memory{}
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memory) ProtoMessage() {}

func (x *Memory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memory.ProtoReflect.Descriptor instead.
func (*Memory) Descriptor() ([]byte, []int) {
	return file_proto_dmgn_v1_dmgn_proto_rawDescGZIP(), []int{0}
}

func (x *Memory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Memory) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Memory) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Memory) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *Memory) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *Memory) GetLinks() []string {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Memory) GetMerkleProof() string {
	if x != nil {
		return x.MerkleProof
	}
	return ""
}

func (x *Memory) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// StoreRequest is the protobuf header sent before shard data on a store stream.
type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	ShardIndex    int32                  `protobuf:"varint,2,opt,name=shard_index,json=shardIndex,proto3" json:"shard_index,omitempty"`
	TotalShards   int32                  `protobuf:"varint,3,opt,name=total_shards,json=totalShards,proto3" json:"total_shards,omitempty"`
	Threshold     int32                  `protobuf:"varint,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	DataLen       int32                  `protobuf:"varint,6,opt,name=data_len,json=dataLen,proto3" json:"data_len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_dmgn_v1_dmgn_proto_rawDescGZIP(), []int{1}
}

func (x *StoreRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *StoreRequest) GetShardIndex() int32 {
	if x != nil {
		return x.ShardIndex
	}
	return 0
}

func (x *StoreRequest) GetTotalShards() int32 {
	if x != nil {
		return x.TotalShards
	}
	return 0
}

func (x *StoreRequest) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *StoreRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *StoreRequest) GetDataLen() int32 {
	if x != nil {
		return x.DataLen
	}
	return 0
}

// StoreResponse is the protobuf response after a store operation.
type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_dmgn_v1_dmgn_proto_rawDescGZIP(), []int{2}
}

func (x *StoreResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// FetchRequest is the protobuf header for a fetch stream.
type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	ShardIndex    int32                  `protobuf:"varint,2,opt,name=shard_index,json=shardIndex,proto3" json:"shard_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_proto_dmgn_v1_dmgn_proto_rawDescGZIP(), []int{3}
}

func (x *FetchRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *FetchRequest) GetShardIndex() int32 {
	if x != nil {
		return x.ShardIndex
	}
	return 0
}

// FetchResponse is the protobuf response for a fetch operation.
type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	MemoryId      string                 `protobuf:"bytes,2,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	ShardIndex    int32                  `protobuf:"varint,3,opt,name=shard_index,json=shardIndex,proto3" json:"shard_index,omitempty"`
	TotalShards   int32                  `protobuf:"varint,4,opt,name=total_shards,json=totalShards,proto3" json:"total_shards,omitempty"`
	Threshold     int32                  `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Checksum      string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	DataLen       int32                  `protobuf:"varint,7,opt,name=data_len,json=dataLen,proto3" json:"data_len,omitempty"`
	Message       string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_proto_dmgn_v1_dmgn_proto_rawDescGZIP(), []int{4}
}

func (x *FetchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FetchResponse) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *FetchResponse) GetShardIndex() int32 {
	if x != nil {
		return x.ShardIndex
	}
	return 0
}

func (x *FetchResponse) GetTotalShards() int32 {
	if x != nil {
		return x.TotalShards
	}
	return 0
}

func (x *FetchResponse) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *FetchResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *FetchResponse) GetDataLen() int32 {
	if x != nil {
		return x.DataLen
	}
	return 0
}

func (x *FetchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GossipMessage is the envelope for gossip broadcasts.
type GossipMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Memory        []byte                 `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	SenderPeerId  string                 `protobuf:"bytes,3,opt,name=sender_peer_id,json=senderPeerId,proto3" json:"sender_peer_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sequence      uint64                 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Edge          []byte                 `protobuf:"bytes,6,opt,name=edge,proto3" json:"edge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_proto_dmgn_v1_dmgn_proto_rawDescGZIP(), []int{5}
}

func (x *GossipMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GossipMessage) GetMemory() []byte {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *GossipMessage) GetSenderPeerId() string {
	if x != nil {
		return x.SenderPeerId
	}
	return ""
}

func (x *GossipMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GossipMessage) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GossipMessage) GetEdge() []byte {
	if x != nil {
		return x.Edge
	}
	return nil
}

// SyncRequest is sent by the initiator to begin delta sync.
type SyncRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SenderPeerId      string                 `protobuf:"bytes,1,opt,name=sender_peer_id,json=senderPeerId,proto3" json:"sender_peer_id,omitempty"`
	VersionVector     map[string]uint64      `protobuf:"bytes,2,rep,name=version_vector,json=versionVector,proto3" json:"version_vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	EdgeVersionVector map[string]uint64      `protobuf:"bytes,3,rep,name=edge_version_vector,json=edgeVersionVector,proto3" json:"edge_version_vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_dmgn_v1_dmgn_proto_rawDescGZIP(), []int{6}
}

func (x *SyncRequest) GetSenderPeerId() string {
	if x != nil {
		return x.SenderPeerId
	}
	return ""
}

func (x *SyncRequest) GetVersionVector() map[string]uint64 {
	if x != nil {
		return x.VersionVector
	}
	return nil
}

func (x *SyncRequest) GetEdgeVersionVector() map[string]uint64 {
	if x != nil {
		return x.EdgeVersionVector
	}
	return nil
}

// SyncResponse is sent by the responder with missing memories and their version vector.
type SyncResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SenderPeerId      string                 `protobuf:"bytes,1,opt,name=sender_peer_id,json=senderPeerId,proto3" json:"sender_peer_id,omitempty"`
	VersionVector     map[string]uint64      `protobuf:"bytes,2,rep,name=version_vector,json=versionVector,proto3" json:"version_vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Memories          [][]byte               `protobuf:"bytes,3,rep,name=memories,proto3" json:"memories,omitempty"`
	Edges             [][]byte               `protobuf:"bytes,4,rep,name=edges,proto3" json:"edges,omitempty"`
	EdgeVersionVector map[string]uint64      `protobuf:"bytes,5,rep,name=edge_version_vector,json=edgeVersionVector,proto3" json:"edge_version_vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_dmgn_v1_dmgn_proto_rawDescGZIP(), []int{7}
}

func (x *SyncResponse) GetSenderPeerId() string {
	if x != nil {
		return x.SenderPeerId
	}
	return ""
}

func (x *SyncResponse) GetVersionVector() map[string]uint64 {
	if x != nil {
		return x.VersionVector
	}
	return nil
}

func (x *SyncResponse) GetMemories() [][]byte {
	if x != nil {
		return x.Memories
	}
	return nil
}

func (x *SyncResponse) GetEdges() [][]byte {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *SyncResponse) GetEdgeVersionVector() map[string]uint64 {
	if x != nil {
		return x.EdgeVersionVector
	}
	return nil
}

// Edge represents a directed relationship between two memories (wire format).
type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Weight        float32                `protobuf:"fixed32,3,opt,name=weight,proto3" json:"weight,omitempty"`
	EdgeType      string                 `protobuf:"bytes,4,opt,name=edge_type,json=edgeType,proto3" json:"edge_type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CreatorPeerId string                 `protobuf:"bytes,6,opt,name=creator_peer_id,json=creatorPeerId,proto3" json:"creator_peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_proto_dmgn_v1_dmgn_proto_rawDescGZIP(), []int{8}
}

func (x *Edge) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *Edge) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *Edge) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Edge) GetEdgeType() string {
	if x != nil {
		return x.EdgeType
	}
	return ""
}

func (x *Edge) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Edge) GetCreatorPeerId() string {
	if x != nil {
		return x.CreatorPeerId
	}
	return ""
}

// QueryFilters holds optional query filters.
type QueryFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	After         int64                  `protobuf:"varint,2,opt,name=after,proto3" json:"after,omitempty"`
	Before        int64                  `protobuf:"varint,3,opt,name=before,proto3" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFilters) Reset() {
	*x = QueryFilters{}
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFilters) ProtoMessage() {}

func (x *QueryFilters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFilters.ProtoReflect.Descriptor instead.
func (*QueryFilters) Descriptor() ([]byte, []int) {
	return file_proto_dmgn_v1_dmgn_proto_rawDescGZIP(), []int{9}
}

func (x *QueryFilters) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QueryFilters) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *QueryFilters) GetBefore() int64 {
	if x != nil {
		return x.Before
	}
	return 0
}

// QueryRequest is the wire format for cross-peer queries.
type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	TextQuery     string                 `protobuf:"bytes,3,opt,name=text_query,json=textQuery,proto3" json:"text_query,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Filters       *QueryFilters          `protobuf:"bytes,5,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_dmgn_v1_dmgn_proto_rawDescGZIP(), []int{10}
}

func (x *QueryRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryRequest) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *QueryRequest) GetTextQuery() string {
	if x != nil {
		return x.TextQuery
	}
	return ""
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryRequest) GetFilters() *QueryFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

// QueryResult holds a single search result.
type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Snippet       string                 `protobuf:"bytes,5,opt,name=snippet,proto3" json:"snippet,omitempty"`
	SourcePeer    string                 `protobuf:"bytes,6,opt,name=source_peer,json=sourcePeer,proto3" json:"source_peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_proto_dmgn_v1_dmgn_proto_rawDescGZIP(), []int{11}
}

func (x *QueryResult) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *QueryResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QueryResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QueryResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *QueryResult) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *QueryResult) GetSourcePeer() string {
	if x != nil {
		return x.SourcePeer
	}
	return ""
}

// QueryResponse is the wire format for cross-peer query results.
type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Results       []*QueryResult         `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	TotalSearched int32                  `protobuf:"varint,3,opt,name=total_searched,json=totalSearched,proto3" json:"total_searched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dmgn_v1_dmgn_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_dmgn_v1_dmgn_proto_rawDescGZIP(), []int{12}
}

func (x *QueryResponse) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryResponse) GetResults() []*QueryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *QueryResponse) GetTotalSearched() int32 {
	if x != nil {
		return x.TotalSearched
	}
	return 0
}

var File_proto_dmgn_v1_dmgn_proto protoreflect.FileDescriptor

const file_proto_dmgn_v1_dmgn_proto_rawDesc = "" +
	"\n" +
	"\x18proto/dmgn/v1/dmgn.proto\x12\admgn.v1\"\xca\x02\n" +
	"\x06Memory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\tembedding\x18\x04 \x03(\x02B\x02\x10\x01R\tembedding\x12+\n" +
	"\x11encrypted_payload\x18\x05 \x01(\fR\x10encryptedPayload\x12\x14\n" +
	"\x05links\x18\x06 \x03(\tR\x05links\x12!\n" +
	"\fmerkle_proof\x18\a \x01(\tR\vmerkleProof\x129\n" +
	"\bmetadata\x18\b \x03(\v2\x1d.dmgn.v1.Memory.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x01\n" +
	"\fStoreRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x1f\n" +
	"\vshard_index\x18\x02 \x01(\x05R\n" +
	"shardIndex\x12!\n" +
	"\ftotal_shards\x18\x03 \x01(\x05R\vtotalShards\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x05R\tthreshold\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12\x19\n" +
	"\bdata_len\x18\x06 \x01(\x05R\adataLen\"A\n" +
	"\rStoreResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\fFetchRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x1f\n" +
	"\vshard_index\x18\x02 \x01(\x05R\n" +
	"shardIndex\"\xf7\x01\n" +
	"\rFetchResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\tmemory_id\x18\x02 \x01(\tR\bmemoryId\x12\x1f\n" +
	"\vshard_index\x18\x03 \x01(\x05R\n" +
	"shardIndex\x12!\n" +
	"\ftotal_shards\x18\x04 \x01(\x05R\vtotalShards\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x05R\tthreshold\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\x12\x19\n" +
	"\bdata_len\x18\a \x01(\x05R\adataLen\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\"\xaf\x01\n" +
	"\rGossipMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\fR\x06memory\x12$\n" +
	"\x0esender_peer_id\x18\x03 \x01(\tR\fsenderPeerId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x04R\bsequence\x12\x12\n" +
	"\x04edge\x18\x06 \x01(\fR\x04edge\"\xe8\x02\n" +
	"\vSyncRequest\x12$\n" +
	"\x0esender_peer_id\x18\x01 \x01(\tR\fsenderPeerId\x12N\n" +
	"\x0eversion_vector\x18\x02 \x03(\v2'.dmgn.v1.SyncRequest.VersionVectorEntryR\rversionVector\x12[\n" +
	"\x13edge_version_vector\x18\x03 \x03(\v2+.dmgn.v1.SyncRequest.EdgeVersionVectorEntryR\x11edgeVersionVector\x1a@\n" +
	"\x12VersionVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aD\n" +
	"\x16EdgeVersionVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\x9d\x03\n" +
	"\fSyncResponse\x12$\n" +
	"\x0esender_peer_id\x18\x01 \x01(\tR\fsenderPeerId\x12O\n" +
	"\x0eversion_vector\x18\x02 \x03(\v2(.dmgn.v1.SyncResponse.VersionVectorEntryR\rversionVector\x12\x1a\n" +
	"\bmemories\x18\x03 \x03(\fR\bmemories\x12\x14\n" +
	"\x05edges\x18\x04 \x03(\fR\x05edges\x12\\\n" +
	"\x13edge_version_vector\x18\x05 \x03(\v2,.dmgn.v1.SyncResponse.EdgeVersionVectorEntryR\x11edgeVersionVector\x1a@\n" +
	"\x12VersionVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aD\n" +
	"\x16EdgeVersionVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xaf\x01\n" +
	"\x04Edge\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x02R\x06weight\x12\x1b\n" +
	"\tedge_type\x18\x04 \x01(\tR\bedgeType\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12&\n" +
	"\x0fcreator_peer_id\x18\x06 \x01(\tR\rcreatorPeerId\"P\n" +
	"\fQueryFilters\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05after\x18\x02 \x01(\x03R\x05after\x12\x16\n" +
	"\x06before\x18\x03 \x01(\x03R\x06before\"\xb1\x01\n" +
	"\fQueryRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12 \n" +
	"\tembedding\x18\x02 \x03(\x02B\x02\x10\x01R\tembedding\x12\x1d\n" +
	"\n" +
	"text_query\x18\x03 \x01(\tR\ttextQuery\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12/\n" +
	"\afilters\x18\x05 \x01(\v2\x15.dmgn.v1.QueryFiltersR\afilters\"\xad\x01\n" +
	"\vQueryResult\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\asnippet\x18\x05 \x01(\tR\asnippet\x12\x1f\n" +
	"\vsource_peer\x18\x06 \x01(\tR\n" +
	"sourcePeer\"\x81\x01\n" +
	"\rQueryResponse\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12.\n" +
	"\aresults\x18\x02 \x03(\v2\x14.dmgn.v1.QueryResultR\aresults\x12%\n" +
	"\x0etotal_searched\x18\x03 \x01(\x05R\rtotalSearchedB0Z.github.com/nnlgsakib/dmgn/proto/dmgn/v1;dmgnpbb\x06proto3"

var (
	file_proto_dmgn_v1_dmgn_proto_rawDescOnce sync.Once
	file_proto_dmgn_v1_dmgn_proto_rawDescData []byte
)

func file_proto_dmgn_v1_dmgn_proto_rawDescGZIP() []byte {
	file_proto_dmgn_v1_dmgn_proto_rawDescOnce.Do(func() {
		file_proto_dmgn_v1_dmgn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dmgn_v1_dmgn_proto_rawDesc), len(file_proto_dmgn_v1_dmgn_proto_rawDesc)))
	})
	return file_proto_dmgn_v1_dmgn_proto_rawDescData
}

var file_proto_dmgn_v1_dmgn_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_dmgn_v1_dmgn_proto_goTypes = []any{
	(*Memory)(nil),        // 0: dmgn.v1.Memory
	(*StoreRequest)(nil),  // 1: dmgn.v1.StoreRequest
	(*StoreResponse)(nil), // 2: dmgn.v1.StoreResponse
	(*FetchRequest)(nil),  // 3: dmgn.v1.FetchRequest
	(*FetchResponse)(nil), // 4: dmgn.v1.FetchResponse
	(*GossipMessage)(nil), // 5: dmgn.v1.GossipMessage
	(*SyncRequest)(nil),   // 6: dmgn.v1.SyncRequest
	(*SyncResponse)(nil),  // 7: dmgn.v1.SyncResponse
	(*Edge)(nil),          // 8: dmgn.v1.Edge
	(*QueryFilters)(nil),  // 9: dmgn.v1.QueryFilters
	(*QueryRequest)(nil),  // 10: dmgn.v1.QueryRequest
	(*QueryResult)(nil),   // 11: dmgn.v1.QueryResult
	(*QueryResponse)(nil), // 12: dmgn.v1.QueryResponse
	nil,                   // 13: dmgn.v1.Memory.MetadataEntry
	nil,                   // 14: dmgn.v1.SyncRequest.VersionVectorEntry
	nil,                   // 15: dmgn.v1.SyncRequest.EdgeVersionVectorEntry
	nil,                   // 16: dmgn.v1.SyncResponse.VersionVectorEntry
	nil,                   // 17: dmgn.v1.SyncResponse.EdgeVersionVectorEntry
}
var file_proto_dmgn_v1_dmgn_proto_depIdxs = []int32{
	13, // 0: dmgn.v1.Memory.metadata:type_name -> dmgn.v1.Memory.MetadataEntry
	14, // 1: dmgn.v1.SyncRequest.version_vector:type_name -> dmgn.v1.SyncRequest.VersionVectorEntry
	15, // 2: dmgn.v1.SyncRequest.edge_version_vector:type_name -> dmgn.v1.SyncRequest.EdgeVersionVectorEntry
	16, // 3: dmgn.v1.SyncResponse.version_vector:type_name -> dmgn.v1.SyncResponse.VersionVectorEntry
	17, // 4: dmgn.v1.SyncResponse.edge_version_vector:type_name -> dmgn.v1.SyncResponse.EdgeVersionVectorEntry
	9,  // 5: dmgn.v1.QueryRequest.filters:type_name -> dmgn.v1.QueryFilters
	11, // 6: dmgn.v1.QueryResponse.results:type_name -> dmgn.v1.QueryResult
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_dmgn_v1_dmgn_proto_init() }
func file_proto_dmgn_v1_dmgn_proto_init() {
	if File_proto_dmgn_v1_dmgn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dmgn_v1_dmgn_proto_rawDesc), len(file_proto_dmgn_v1_dmgn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dmgn_v1_dmgn_proto_goTypes,
		DependencyIndexes: file_proto_dmgn_v1_dmgn_proto_depIdxs,
		MessageInfos:      file_proto_dmgn_v1_dmgn_proto_msgTypes,
	}.Build()
	File_proto_dmgn_v1_dmgn_proto = out.File
	file_proto_dmgn_v1_dmgn_proto_goTypes = nil
	file_proto_dmgn_v1_dmgn_proto_depIdxs = nil
}
